
export const FETCH_WEATHER_REPORT_START = "FETCH_WEATHER_REPORT_START";
export const FETCH_WEATHER_REPORT_SUCCESS = "FETCH_WEATHER_REPORT_SUCCESS";
export const FETCH_WEATHER_REPORT_ERROR = "FETCH_WEATHER_REPORT_ERROR";
export const FETCH_WEATHER_DAILY_DATA = "ETCH_WEATHER_DAILY_DATA";
export const FETCH_WEATHER_DAILY_DATA_SUCCESS = "FETCH_WEATHER_DAILY_DATA_SUCCESS";
export const FETCH_WEATHER_DAILY_DATA_ERROR = "FETCH_WEATHER_DAILY_DATA_ERROR";